// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace SeleniumRunner
{
    [TestFixture]
    public class EnterVehicleDataTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void enterVehicleData()
        {
            driver.Navigate().GoToUrl("http://sampleapp.tricentis.com/101/");
            driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
            driver.FindElement(By.Id("nav_automobile")).Click();
            driver.FindElement(By.Id("make")).Click();
            {
                var dropdown = driver.FindElement(By.Id("make"));
                dropdown.FindElement(By.XPath("//option[. = 'BMW']")).Click();
            }
            driver.FindElement(By.CssSelector("#make > option:nth-child(3)")).Click();
            driver.FindElement(By.Id("engineperformance")).Click();
            driver.FindElement(By.Id("engineperformance")).SendKeys("5");
            driver.FindElement(By.Id("dateofmanufacture")).Click();
            driver.FindElement(By.Id("dateofmanufacture")).SendKeys("12/12/2012");
            driver.FindElement(By.Id("numberofseats")).Click();
            {
                var dropdown = driver.FindElement(By.Id("numberofseats"));
                dropdown.FindElement(By.XPath("//option[. = '2']")).Click();
            }
            driver.FindElement(By.CssSelector("#numberofseats > option:nth-child(3)")).Click();
            driver.FindElement(By.Id("fuel")).Click();
            {
                var dropdown = driver.FindElement(By.Id("fuel"));
                dropdown.FindElement(By.XPath("//option[. = 'Gas']")).Click();
            }
            driver.FindElement(By.CssSelector("#fuel > option:nth-child(5)")).Click();
            driver.FindElement(By.Id("listprice")).Click();
            driver.FindElement(By.Id("listprice")).SendKeys("50000");
            driver.FindElement(By.Id("licenseplatenumber")).Click();
            driver.FindElement(By.Id("licenseplatenumber")).SendKeys("qTest123");
            driver.FindElement(By.Id("annualmileage")).Click();
            driver.FindElement(By.Id("annualmileage")).SendKeys("12000");
            Assert.That(driver.FindElement(By.CssSelector(".zero")).Text, Is.EqualTo("0"));
        }
    }
}
